### ISSUE TITLE
Unable to upload to App Store ERROR ITMS-90035: Invalid Signature. Code object is not signed at all

### ISSUE THREAD

**Issue by punch1985** [loadsmart/rn-salesforce-chat#23] opened 2021-05-28 12:35 UTC
Xcode 12.5 / 12.4
React native 0.61.5
rn-salesforce-chat 2.0.1

ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [XXXX.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

**Comment by lenoirzamboni** [comment] 2021-05-28 19:39
@punch1985 Hello! Could you please provide more info about the issue:

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]

**rn-salesforce-chat version (please complete the following information):**
 - Version: [e.g. v2.0.0]

**Screenshots**
If applicable, add screenshots to help explain your problem.

Thanks!

**Comment by punch1985** [comment] 2021-05-29 01:33
**Describe the issue**

Error reported when upload ipa to App Store Connect.
I have tried to upload via Xcode and Transporter but both failed.
here is the full error message:

> ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [RentPay.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

Xcode version 12.5

To Reproduce
Steps to reproduce the behavior:

integrate rn-salesforce-chat
clean and archive using Xcode
In Xcode's Organizer, select the archive and press "Distribute App",
follow the steps to choose certificate and profile, then press upload.

I have also using AppCenter to build and deliver to App Store Connect (using Xcode 12.4).
It does not report error but the build is not appear in App Store Connect.

**Smartphone (please complete the following information):**

iPhone 12
Any iOS Device (arm64, armv7)

**rn-salesforce-chat version (please complete the following information):**

Version: 2.0.1

**Screenshots**

<img width="771" alt="Screen Shot 2021-05-29 at 9 27 48 am" src="https://user-images.githubusercontent.com/5991219/120054093-72c77600-c060-11eb-83dc-bb1564d9b566.png">

**Comment by punch1985** [comment] 2021-05-29 02:09
@lenoirzamboni I found the solution

I follow the salesforce developer guideline to add a run script to in my project, except I need to change the path for the script to

../node_modules/@loadsmart/rn-salesforce-chat/ios/Frameworks/ServiceCore.framework/prepare-framework

It would be good if this included in the README file 

see also:
https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/ios_prepare_for_appstore.htm

**Comment by lenoirzamboni** [comment] 2021-06-02 11:04
@punch1985 Thanks for reporting and finding the solution. We will add this to the README soon.

**Comment by lenoirzamboni** [comment] 2021-07-29 14:57
The documentation for this was added on version [3.0.0](https://github.com/loadsmart/rn-salesforce-chat#prepare-app-submission-for-ios).

Closing issue.

**Closed by lenoirzamboni** 2021-07-29 14:57 UTC
